### ISSUE TITLE
3D simulation not working: Warp CUDA error 209: no kernel image is available for execution on the device 

### ISSUE THREAD

**Issue by subash-19** [maria-korosteleva/GarmentCode#35]
![issue1(3d_not_working)](https://github.com/user-attachments/assets/9681b710-56b5-474a-8958-89dbb8b85d62)
i tried running Garment code in my local and its working. But the issue is 3D draping is not working. I tried with the default settings. Yet same issue shown in the above image. I tried i your hosted version too. There also i get the same error.

Here is the log i get :
"D:\garment_code\NvidiaWarp-GarmentCode\warp\context.py:1897: UserWarning: Support for stream ordered memory allocators was not detected on device 0. This can prevent the use of graphs and/or result in poor performance. Is the UVM driver enabled?
  warp.utils.warn(
Warp 1.0.0-beta.6 initialized:
   CUDA Toolkit: 12.5, Driver: 12.5
   Devices:
     "cpu"    | Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
     "cuda:0" | NVIDIA GeForce MX130 (sm_50)
   Kernel cache: C:\Users\AppData\Local\NVIDIA Corporation\warp\Cache\1.0.0-beta.6
NiceGUI ready to go on http://localhost:8080, http://169.254.207.216:8080, http://169.254.22.165:8080, http://169.254.220.155:8080, and http://192.168.29.68:8080
INFO::Updating pattern...
INFO::Updating pattern...
INFO::Updating 3D...
Success! Configured_design saved to D:\garment_code\GarmentCode\tmp_gui\downloads\8QJ8DLXRRFWPA9RWQKYY\Configured_design
D:\garment_code\GarmentCode\pygarment\meshgen\render\texture_utils.py:161: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  fig, ax = plt.subplots()
Module warp.sim.inertia load on device 'cuda:0' took 66.31 ms
Warp CUDA error 209: no kernel image is available for execution on the device (D:\garment_code\NvidiaWarp-GarmentCode\warp\native\sort.cu:45)
Warp CUDA error 209: no kernel image is available for execution on the device (D:\garment_code\NvidiaWarp-GarmentCode\warp\native\sort.cu:82)
Module warp.collision.panel_assignment load on device 'cuda:0' took 31.07 ms
Warp CUDA error 700: an illegal memory access was encountered (D:\garment_code\NvidiaWarp-GarmentCode\warp\native\warp.cu:273)
right_btorso:body
Warp CUDA error 700: an illegal memory access was encountered (D:\garment_code\NvidiaWarp-GarmentCode\warp\native\warp.cu:217)
Traceback (most recent call last):
  File "D:\garment_code\GarmentCode\gui\callbacks.py", line 681, in update_3d_scene
    await self.loop.run_in_executor(self._async_executor, self._sync_update_3d)
  File "C:\Users\miniconda3\envs\garment\Lib\concurrent\futures\thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\garment_code\GarmentCode\gui\callbacks.py", line 712, in _sync_update_3d
    path, filename = self.pattern_state.drape_3d()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\garment_code\GarmentCode\gui\gui_pattern.py", line 234, in drape_3d
    run_sim(
  File "D:\garment_code\GarmentCode\pygarment\meshgen\simulation.py", line 178, in run_sim
    garment = Cloth(cloth_name, config, paths, caching=store_usd)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\garment_code\GarmentCode\pygarment\meshgen\garment.py", line 47, in __init__
    self.build_stage(config)
  File "D:\garment_code\GarmentCode\pygarment\meshgen\garment.py", line 185, in build_stage
    cloth_reference_labels, body_parts = assign.panel_assignment(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\garment_code\NvidiaWarp-GarmentCode\warp\collision\panel_assignment.py", line 183, in panel_assignment
    p_verts = wp.array(panel_verts[p_vert_index], dtype=wp.vec3, device=device)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\garment_code\NvidiaWarp-GarmentCode\warp\types.py", line 1356, in __init__
    self._init_from_data(data, dtype, shape, device, copy, pinned)
  File "D:\garment_code\NvidiaWarp-GarmentCode\warp\types.py", line 1494, in _init_from_data
    self._init_new(dtype, shape, None, device, pinned)
  File "D:\garment_code\NvidiaWarp-GarmentCode\warp\types.py", line 1563, in _init_new
    raise RuntimeError(f"Array allocation failed on device: {device} for {capacity} bytes")
RuntimeError: Array allocation failed on device: cuda:0 for 11292 bytes
Array allocation failed on device: cuda:0 for 11292 bytes
Warp CUDA error 700: an illegal memory access was encountered (D:\garment_code\NvidiaWarp-GarmentCode\warp\native\warp.cu:245)
Warp CUDA error 700: an illegal memory access was encountered (D:\garment_code\NvidiaWarp-GarmentCode\warp\native\warp.cu:245)
Warp CUDA error 700: an illegal memory access was encountered (D:\garment_code\NvidiaWarp-GarmentCode\warp\native\warp.cu:245)
Warp CUDA error 700: an illegal memory access was encountered (D:\garment_code\NvidiaWarp-GarmentCode\warp\native\warp.cu:245)
Warp CUDA error 700: an illegal memory access was encountered (D:\garment_code\NvidiaWarp-GarmentCode\warp\native\warp.cu:245)
Warp CUDA error 700: an illegal memory access was encountered (D:\garment_code\NvidiaWarp-GarmentCode\warp\native\warp.cu:245)
Warp CUDA error 700: an illegal memory access was encountered (D:\garment_code\NvidiaWarp-GarmentCode\warp\native\warp.cu:245)
Warp CUDA error 700: an illegal memory access was encountered (D:\garment_code\NvidiaWarp-GarmentCode\warp\native\warp.cu:245)
Warp CUDA error 700: an illegal memory access was encountered (D:\garment_code\NvidiaWarp-GarmentCode\warp\native\warp.cu:245)
Warp CUDA error 700: an illegal memory access was encountered (D:\garment_code\NvidiaWarp-GarmentCode\warp\native\warp.cu:245)
Warp CUDA error 700: an illegal memory access was encountered (D:\garment_code\NvidiaWarp-GarmentCode\warp\native\warp.cu:245)
Warp CUDA error 700: an illegal memory access was encountered (D:\garment_code\NvidiaWarp-GarmentCode\warp\native\warp.cu:245)
"

**Comment by maria-korosteleva** [comment]
3D drape on the public online version occasionally fails due to a different (known) issue on the server side. It is usually fixed with the server restart, which I do when the issue reappears. However, it's not your case. 

`CUDA error 209: no kernel image is available for execution on the device` points to the CUDA driver compatibility issues on your device

A quick Google search points to these posts:
https://stackoverflow.com/questions/67825986/nvidia-cuda-error-no-kernel-image-is-available-for-execution-on-the-device
https://forums.developer.nvidia.com/t/runtimeerror-cuda-error-no-kernel-image-is-available-for-execution-on-the-device/167708/7

I hope one of them will help resolve your problem locally

**Comment by Sanjaypranav** [comment]
After passing permisson chmod to current file still i got the `pacman` error 

```juu/5C2072E62072C6941/Yoko/NvidiaWarp-GarmentCode/warp/native"  -I"/media/senjuu/5C2072E62072C6941/Yoko/NvidiaWarp-GarmentCode/external/llvm-project/out/install/release-x86_64/include" -I"/media/senjuu/5C2072E62072C6941/Yoko/NvidiaWarp-GarmentCode/_build/host-deps/llvm-project/release-x86_64/include" -c "/media/senjuu/5C2072E62072C6941/Yoko/NvidiaWarp-GarmentCode/warp/native/marching.cpp" -o "/media/senjuu/5C2072E62072C6941/Yoko/NvidiaWarp-GarmentCode/warp/native/marching.cpp.o"
g++  -O3 -DNDEBUG -DWP_ENABLE_DEBUG=0 -DWP_ENABLE_CUDA=0 -DWP_ENABLE_CUTLASS=1 -DWP_ENABLE_CUDA_COMPATIBILITY=0 -fPIC -fvisibility=hidden --std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0 -I"/media/senjuu/5C2072E62072C6941/Yoko/NvidiaWarp-GarmentCode/warp/native"  -I"/media/senjuu/5C2072E62072C6941/Yoko/NvidiaWarp-GarmentCode/external/llvm-project/out/install/release-x86_64/include" -I"/media/senjuu/5C2072E62072C6941/Yoko/NvidiaWarp-GarmentCode/_build/host-deps/llvm-project/release-x86_64/include" -c "/media/senjuu/5C2072E62072C6941/Yoko/NvidiaWarp-GarmentCode/warp/native/cutlass_gemm.cpp" -o "/media/senjuu/5C2072E62072C6941/Yoko/NvidiaWarp-GarmentCode/warp/native/cutlass_gemm.cpp.o"
build took 12866.47 ms
g++  -shared -Wl,-rpath,'$ORIGIN' -Wl,--no-undefined -Wl,--exclude-libs,ALL -o '/media/senjuu/5C2072E62072C6941/Yoko/NvidiaWarp-GarmentCode/warp/bin/warp.so' "/media/senjuu/5C2072E62072C6941/Yoko/NvidiaWarp-GarmentCode/warp/native/warp.cpp.o" "/media/senjuu/5C2072E62072C6941/Yoko/NvidiaWarp-GarmentCode/warp/native/crt.cpp.o" "/media/senjuu/5C2072E62072C6941/Yoko/NvidiaWarp-GarmentCode/warp/native/cuda_util.cpp.o" "/media/senjuu/5C2072E62072C6941/Yoko/NvidiaWarp-GarmentCode/warp/native/mesh.cpp.o" "/media/senjuu/5C2072E62072C6941/Yoko/NvidiaWarp-GarmentCode/warp/native/hashgrid.cpp.o" "/media/senjuu/5C2072E62072C6941/Yoko/NvidiaWarp-GarmentCode/warp/native/reduce.cpp.o" "/media/senjuu/5C2072E62072C6941/Yoko/NvidiaWarp-GarmentCode/warp/native/runlength_encode.cpp.o" "/media/senjuu/5C2072E62072C6941/Yoko/NvidiaWarp-GarmentCode/warp/native/sort.cpp.o" "/media/senjuu/5C2072E62072C6941/Yoko/NvidiaWarp-GarmentCode/warp/native/sparse.cpp.o" "/media/senjuu/5C2072E62072C6941/Yoko/NvidiaWarp-GarmentCode/warp/native/volume.cpp.o" "/media/senjuu/5C2072E62072C6941/Yoko/NvidiaWarp-GarmentCode/warp/native/marching.cpp.o" "/media/senjuu/5C2072E62072C6941/Yoko/NvidiaWarp-GarmentCode/warp/native/cutlass_gemm.cpp.o"
strip --strip-all --keep-symbol=__jit_debug_register_code --keep-symbol=__jit_debug_descriptor /media/senjuu/5C2072E62072C6941/Yoko/NvidiaWarp-GarmentCode/warp/bin/warp.so
link took 68.56 ms
Warp Clang/LLVM build error: [Errno 13] Permission denied: './tools/packman/packman'
```

any possible solution to fix this issue ?

**Comment by Sanjaypranav** [comment]
issue solved :+1:  by running `pacman` from cli `./tools/packman/packman` thanks

**Comment by subash-19** [comment]
Now its working. Tried with a different system and it worked. I think my system has an issue.
